name: 🤖 Support Request
description: Support request for robot maintenance
assignees: violadelbono
body:
- type: markdown
  attributes:
    value: |
      ⚠
      Please, remember to indicate the name of your robot by assigning the proper label 🔖
      Verify first that your issue is not [already reported on GitHub][issue search].
      Also test if the latest release and devel branch are affected too.

      [issue search]: https://github.com/robotology/icub-tech-support/search?q=is%3Aissue&type=issues    
- type: textarea
  attributes:
    label: Request/Failure description
    description: Summarize the request concisely.
  validations:
    required: true
- type: textarea
  attributes:
    label: Detailed context
    description: Provide a more detailed description of the problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Please attach here any material you may consider useful (pictures, screenshots, logs, etc.).
